[workspace]

resolver = "2"

members = ["tests", "reflected", "reflected_proc"]

default-members = ["reflected"]

[workspace.dependencies]
chrono = "0.4"
rust_decimal = "1.34"
fake = "4.2"

#reflected_proc = { path = "reflected_proc" }
reflected_proc = "=0.10.2"
